In [1]:
import numpy as np
import pandas as pd
import pyarrow.parquet as pq

In [2]:
podaci_38 = pd.read_parquet("C:/Users/vvrhovec/Veronika/kodovi/podaci_art38.parquet")
podaci_39 = pd.read_parquet("C:/Users/vvrhovec/Veronika/kodovi/podaci_art39.parquet")
podaci_40 = pd.read_parquet("C:/Users/vvrhovec/Veronika/kodovi/podaci_art40.parquet")
podaci_41 = pd.read_parquet("C:/Users/vvrhovec/Veronika/kodovi/podaci_art41.parquet")
podaci_57 = pd.read_parquet("C:/Users/vvrhovec/Veronika/kodovi/podaci_art57.parquet")

C:\Users\vvrhovec\AppData\Local\Continuum\miniconda3\envs\okolina\lib\site-packages\pyarrow\pandas_compat.py:708: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels = getattr(columns, 'labels', None) or [
C:\Users\vvrhovec\AppData\Local\Continuum\miniconda3\envs\okolina\lib\site-packages\pyarrow\pandas_compat.py:735: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return pd.MultiIndex(levels=new_levels, labels=labels, names=columns.names)
C:\Users\vvrhovec\AppData\Local\Continuum\miniconda3\envs\okolina\lib\site-packages\pyarrow\pandas_compat.py:752: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels

In [8]:
podaci_57

                redna_cena  akcijska_cena  n_trgovin    kol  Monday  Tuesday  \
art datum
57  2016-01-02       0.081          0.081        103   73.0       0        0
    2016-01-03       0.082          0.082        101    4.0       0        0
    2016-01-04       0.080          0.080        102   34.0       1        0
    2016-01-05       0.082          0.082        101   27.0       0        1
    2016-01-06       0.080          0.080        101   61.0       0        0
    2016-01-07       0.081          0.081        102   60.0       0        0
    2016-01-08       0.080          0.080        103   17.0       0        0
    2016-01-09       0.081          0.081        101   56.0       0        0
    2016-01-10       0.080          0.080        100   45.0       0        0
    2016-01-11       0.081          0.081        104   82.0       1        0
    2016-01-12       0.085          0.085        103    4.0       0        1
    2016-01-13       0.082          0.082        103   20.0       0        0
    2016-01-14       0.081          0.081        104   69.0       0        0
    2016-01-15       0.081          0.081        103   47.0       0        0
    2016-01-16       0.080          0.080        101   61.0       0        0
    2016-01-17       0.082          0.082        102   14.0       0        0
    2016-01-18       0.081          0.081        103   33.0       1        0
    2016-01-19       0.081          0.081        104   67.0       0        1
    2016-01-20       0.080          0.080        102   81.0       0        0
    2016-01-21       0.080          0.080        103   86.0       0        0
    2016-01-22       0.080          0.080        104   79.0       0        0
    2016-01-23       0.081          0.081        103   51.0       0        0
    2016-01-25       0.080          0.080        104   27.0       1        0
    2016-01-26       0.081          0.081        103   44.0       0        1
    2016-01-27       0.081          0.081        104   82.0       0        0
    2016-01-28       0.081          0.081        105   41.0       0        0
    2016-01-29       0.080          0.080        106  148.0       0        0
    2016-01-30       0.081          0.081        105   56.0       0        0
    2016-01-31       0.082          0.082        104   17.0       0        0
    2016-02-01       0.081          0.081        104   43.0       1        0
...                    ...            ...        ...    ...     ...      ...
    2018-04-26       0.080          0.080         76  142.0       0        0
    2018-04-27       0.080          0.080         76   35.0       0        0
    2018-04-28       0.081          0.081         76   73.0       0        0
    2018-04-29       0.080          0.080         74   36.0       0        0
    2018-05-02       0.080          0.080         75   34.0       0        0
    2018-05-03       0.080          0.080         76  126.0       0        0
    2018-05-04       0.080          0.080         77   88.0       0        0
    2018-05-05       0.080          0.080         75   24.0       0        0
    2018-05-06       0.080          0.080         76   24.0       0        0
    2018-05-07       0.081          0.081         78   36.0       1        0
    2018-05-08       0.080          0.080         76   79.0       0        1
    2018-05-09       0.080          0.080         74   79.0       0        0
    2018-05-10       0.080          0.080         75   53.0       0        0
    2018-05-11       0.080          0.080         76   71.0       0        0
    2018-05-13       0.081          0.081         72   27.0       0        0
    2018-05-14       0.081          0.081         72   69.0       1        0
    2018-05-15       0.080          0.080         73  287.0       0        1
    2018-05-17       0.080          0.080         75  118.0       0        0
    2018-05-18       0.080          0.080         75   84.0       0        0
    2018-05-19       0.081          0.081         74   32.0       0        0
    2018-05-21       0.080          0.080         75  166.0       1        0
    2018-05-22       0.082          0.082         74   26.0       0        1
    2018-05-23       0.080          0.080         74  216.0       0        0
    2018-05-24       0.080          0.080         73  130.0       0        0
    2018-05-25       0.081          0.081         74   22.0       0        0
    2018-05-26       0.080          0.080         75   63.0       0        0
    2018-05-27       0.080          0.080         72   22.0       0        0
    2018-05-28       0.081          0.081         74   78.0       1        0
    2018-05-30       0.080          0.080         71   79.0       0        0
    2018-05-31       0.080          0.080         73   94.0       0        0

                Wednesday  Thursday  Friday  Saturday  Sunday  Weekend
art datum
57  2016-01-02          0         0       0         1       0        1
    2016-01-03          0         0       0         0       1        1
    2016-01-04          0         0       0         0       0        0
    2016-01-05          0         0       0         0       0        0
    2016-01-06          1         0       0         0       0        0
    2016-01-07          0         1       0         0       0        0
    2016-01-08          0         0       1         0       0        0
    2016-01-09          0         0       0         1       0        1
    2016-01-10          0         0       0         0       1        1
    2016-01-11          0         0       0         0       0        0
    2016-01-12          0         0       0         0       0        0
    2016-01-13          1         0       0         0       0        0
    2016-01-14          0         1       0         0       0        0
    2016-01-15          0         0       1         0       0        0
    2016-01-16          0         0       0         1       0        1
    2016-01-17          0         0       0         0       1        1
    2016-01-18          0         0       0         0       0        0
    2016-01-19          0         0       0         0       0        0
    2016-01-20          1         0       0         0       0        0
    2016-01-21          0         1       0         0       0        0
    2016-01-22          0         0       1         0       0        0
    2016-01-23          0         0       0         1       0        1
    2016-01-25          0         0       0         0       0        0
    2016-01-26          0         0       0         0       0        0
    2016-01-27          1         0       0         0       0        0
    2016-01-28          0         1       0         0       0        0
    2016-01-29          0         0       1         0       0        0
    2016-01-30          0         0       0         1       0        1
    2016-01-31          0         0       0         0       1        1
    2016-02-01          0         0       0         0       0        0
...                   ...       ...     ...       ...     ...      ...
    2018-04-26          0         1       0         0       0        0
    2018-04-27          0         0       1         0       0        0
    2018-04-28          0         0       0         1       0        1
    2018-04-29          0         0       0         0       1        1
    2018-05-02          1         0       0         0       0        0
    2018-05-03          0         1       0         0       0        0
    2018-05-04          0         0       1         0       0        0
    2018-05-05          0         0       0         1       0        1
    2018-05-06          0         0       0         0       1        1
    2018-05-07          0         0       0         0       0        0
    2018-05-08          0         0       0         0       0        0
    2018-05-09          1         0       0         0       0        0
    2018-05-10          0         1       0         0       0        0
    2018-05-11          0         0       1         0       0        0
    2018-05-13          0         0       0         0       1        1
    2018-05-14          0         0       0         0       0        0
    2018-05-15          0         0       0         0       0        0
    2018-05-17          0         1       0         0       0        0
    2018-05-18          0         0       1         0       0        0
    2018-05-19          0         0       0         1       0        1
    2018-05-21          0         0       0         0       0        0
    2018-05-22          0         0       0         0       0        0
    2018-05-23          1         0       0         0       0        0
    2018-05-24          0         1       0         0       0        0
    2018-05-25          0         0       1         0       0        0
    2018-05-26          0         0       0         1       0        1
    2018-05-27          0         0       0         0       1        1
    2018-05-28          0         0       0         0       0        0
    2018-05-30          1         0       0         0       0        0
    2018-05-31          0         1       0         0       0        0

[801 rows x 12 columns]